/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.yoshibv.contasoc.ventanas;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author jomaa
 */
@SuppressWarnings("serial")
public class Inicio extends javax.swing.JFrame {
    
    private int xMouse, yMouse;
    
    /**
     * Creates new form Interfaz
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo_small.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolBar = new javax.swing.JToolBar();
        jLabelLogo = new javax.swing.JLabel();
        toolBarFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        MinimizeBtn = new javax.swing.JPanel();
        MinimizeTxt = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JPanel();
        ExitTxt = new javax.swing.JLabel();
        SociosBtn = new javax.swing.JPanel();
        SociosIcon = new javax.swing.JLabel();
        SociosTxt = new javax.swing.JLabel();
        IngresosBtn = new javax.swing.JPanel();
        IngresosIcon = new javax.swing.JLabel();
        IngresosTxt = new javax.swing.JLabel();
        PagosBtn = new javax.swing.JPanel();
        PagosIcon = new javax.swing.JLabel();
        PagosTxt = new javax.swing.JLabel();
        InformeBtn = new javax.swing.JPanel();
        InformeIcon = new javax.swing.JLabel();
        InformeTxt = new javax.swing.JLabel();
        ListaEsperaBtn = new javax.swing.JPanel();
        ListaEsperaIcon = new javax.swing.JLabel();
        ListaEsperaTxt = new javax.swing.JLabel();
        CopyrightTxt = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToolBar.setBackground(new java.awt.Color(255, 255, 255));
        ToolBar.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.windowBorder));
        ToolBar.setFloatable(false);
        ToolBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToolBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ToolBarMouseDragged(evt);
            }
        });

        jLabelLogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_small.png"))); // NOI18N
        jLabelLogo.setText("Contasoc - Inicio");
        jLabelLogo.setIconTextGap(6);
        jLabelLogo.setMaximumSize(new java.awt.Dimension(86, 32));
        jLabelLogo.setMinimumSize(new java.awt.Dimension(86, 32));
        jLabelLogo.setName(""); // NOI18N
        jLabelLogo.setPreferredSize(new java.awt.Dimension(150, 32));
        jLabelLogo.setRequestFocusEnabled(false);
        ToolBar.add(jLabelLogo);
        jLabelLogo.getAccessibleContext().setAccessibleName("");

        toolBarFiller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toolBarFiller.setFocusable(true);
        ToolBar.add(toolBarFiller);

        MinimizeBtn.setBackground(new java.awt.Color(255, 255, 255));
        MinimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeBtn.setMaximumSize(new java.awt.Dimension(32, 32));
        MinimizeBtn.setMinimumSize(new java.awt.Dimension(32, 32));
        MinimizeBtn.setPreferredSize(new java.awt.Dimension(32, 32));
        MinimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeBtnMouseExited(evt);
            }
        });
        MinimizeBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));

        MinimizeTxt.setBackground(new java.awt.Color(255, 255, 255));
        MinimizeTxt.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        MinimizeTxt.setText("—");
        MinimizeTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MinimizeTxt.setMaximumSize(new java.awt.Dimension(32, 32));
        MinimizeTxt.setMinimumSize(new java.awt.Dimension(32, 32));
        MinimizeTxt.setPreferredSize(new java.awt.Dimension(32, 32));
        MinimizeBtn.add(MinimizeTxt);

        ToolBar.add(MinimizeBtn);

        ExitBtn.setBackground(new java.awt.Color(255, 255, 255));
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.setMaximumSize(new java.awt.Dimension(32, 32));
        ExitBtn.setMinimumSize(new java.awt.Dimension(32, 32));
        ExitBtn.setPreferredSize(new java.awt.Dimension(32, 32));
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnMouseExited(evt);
            }
        });
        ExitBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));

        ExitTxt.setBackground(new java.awt.Color(255, 255, 255));
        ExitTxt.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        ExitTxt.setText("X");
        ExitTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ExitTxt.setMaximumSize(new java.awt.Dimension(32, 32));
        ExitTxt.setMinimumSize(new java.awt.Dimension(32, 32));
        ExitTxt.setPreferredSize(new java.awt.Dimension(32, 32));
        ExitBtn.add(ExitTxt);

        ToolBar.add(ExitBtn);

        getContentPane().add(ToolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        SociosBtn.setBackground(new java.awt.Color(255, 255, 255));
        SociosBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SociosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SociosBtn.setMaximumSize(new java.awt.Dimension(180, 40));
        SociosBtn.setMinimumSize(new java.awt.Dimension(180, 40));
        SociosBtn.setPreferredSize(new java.awt.Dimension(180, 40));
        SociosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SociosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SociosBtnMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	SociosBtnMouseClicked(evt);
            }
        });
        SociosBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        SociosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/socios.png"))); // NOI18N
        SociosBtn.add(SociosIcon);

        SociosTxt.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        SociosTxt.setText("Socios");
        SociosTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SociosTxt.setMaximumSize(new java.awt.Dimension(120, 40));
        SociosTxt.setMinimumSize(new java.awt.Dimension(120, 40));
        SociosTxt.setPreferredSize(new java.awt.Dimension(120, 40));
        SociosBtn.add(SociosTxt);

        getContentPane().add(SociosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 180, 50));

        IngresosBtn.setBackground(new java.awt.Color(255, 255, 255));
        IngresosBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IngresosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresosBtn.setMaximumSize(new java.awt.Dimension(180, 40));
        IngresosBtn.setMinimumSize(new java.awt.Dimension(180, 40));
        IngresosBtn.setPreferredSize(new java.awt.Dimension(180, 40));
        IngresosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IngresosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IngresosBtnMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	IngresosBtnMouseClicked(evt);
            }
        });
        IngresosBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        IngresosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresos.png"))); // NOI18N
        IngresosBtn.add(IngresosIcon);

        IngresosTxt.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        IngresosTxt.setText("Ingresos");
        IngresosTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IngresosTxt.setMaximumSize(new java.awt.Dimension(120, 40));
        IngresosTxt.setMinimumSize(new java.awt.Dimension(120, 40));
        IngresosTxt.setPreferredSize(new java.awt.Dimension(120, 40));
        IngresosBtn.add(IngresosTxt);

        getContentPane().add(IngresosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 180, 50));

        PagosBtn.setBackground(new java.awt.Color(255, 255, 255));
        PagosBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PagosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PagosBtn.setMaximumSize(new java.awt.Dimension(180, 40));
        PagosBtn.setMinimumSize(new java.awt.Dimension(180, 40));
        PagosBtn.setPreferredSize(new java.awt.Dimension(180, 40));
        PagosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PagosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PagosBtnMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	PagosBtnMouseClicked(evt);
            }
        });
        PagosBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        PagosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagos.png"))); // NOI18N
        PagosBtn.add(PagosIcon);

        PagosTxt.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        PagosTxt.setText("Pagos");
        PagosTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PagosTxt.setMaximumSize(new java.awt.Dimension(120, 40));
        PagosTxt.setMinimumSize(new java.awt.Dimension(120, 40));
        PagosTxt.setPreferredSize(new java.awt.Dimension(120, 40));
        PagosBtn.add(PagosTxt);

        getContentPane().add(PagosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 180, 50));

        InformeBtn.setBackground(new java.awt.Color(255, 255, 255));
        InformeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InformeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InformeBtn.setMaximumSize(new java.awt.Dimension(180, 40));
        InformeBtn.setMinimumSize(new java.awt.Dimension(180, 40));
        InformeBtn.setPreferredSize(new java.awt.Dimension(180, 40));
        InformeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InformeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InformeBtnMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	InformeBtnMouseClicked(evt);
            }
        });
        InformeBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        InformeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informe.png"))); // NOI18N
        InformeBtn.add(InformeIcon);

        InformeTxt.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        InformeTxt.setText("Informe");
        InformeTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InformeTxt.setMaximumSize(new java.awt.Dimension(120, 40));
        InformeTxt.setMinimumSize(new java.awt.Dimension(120, 40));
        InformeTxt.setPreferredSize(new java.awt.Dimension(120, 40));
        InformeBtn.add(InformeTxt);

        getContentPane().add(InformeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 180, 50));

        ListaEsperaBtn.setBackground(new java.awt.Color(255, 255, 255));
        ListaEsperaBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListaEsperaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListaEsperaBtn.setMaximumSize(new java.awt.Dimension(180, 40));
        ListaEsperaBtn.setMinimumSize(new java.awt.Dimension(180, 40));
        ListaEsperaBtn.setPreferredSize(new java.awt.Dimension(180, 40));
        ListaEsperaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListaEsperaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ListaEsperaBtnMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	ListaEsperaBtnMouseClicked(evt);
            }
        });
        ListaEsperaBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        ListaEsperaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lista_espera.png"))); // NOI18N
        ListaEsperaBtn.add(ListaEsperaIcon);

        ListaEsperaTxt.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        ListaEsperaTxt.setText("Lista Espera");
        ListaEsperaTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ListaEsperaTxt.setMaximumSize(new java.awt.Dimension(120, 40));
        ListaEsperaTxt.setMinimumSize(new java.awt.Dimension(120, 40));
        ListaEsperaTxt.setPreferredSize(new java.awt.Dimension(120, 40));
        ListaEsperaBtn.add(ListaEsperaTxt);

        getContentPane().add(ListaEsperaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 180, 50));

        CopyrightTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CopyrightTxt.setText("Copyright © 2023 by YoshiBv");
        getContentPane().add(CopyrightTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 250, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg.png"))); // NOI18N
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.windowBorder));
        jLabelFondo.setPreferredSize(new java.awt.Dimension(960, 600));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToolBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolBarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_ToolBarMouseDragged

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void MinimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimizeBtnMouseClicked

    private void ExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseEntered
        // TODO add your handling code here:
        ExitBtn.setBackground(Color.RED);
    }//GEN-LAST:event_ExitBtnMouseEntered

    private void ExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseExited
        // TODO add your handling code here:
        ExitBtn.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_ExitBtnMouseExited

    private void MinimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeBtnMouseEntered
        // TODO add your handling code here:
        MinimizeBtn.setBackground(Color.decode("#287AE9"));
    }//GEN-LAST:event_MinimizeBtnMouseEntered

    private void MinimizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeBtnMouseExited
        // TODO add your handling code here:
        MinimizeBtn.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_MinimizeBtnMouseExited

    private void SociosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SociosBtnMouseEntered
        // TODO add your handling code here:
        SociosBtn.setBackground(Color.decode("#CACACA"));
    }//GEN-LAST:event_SociosBtnMouseEntered

    private void SociosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SociosBtnMouseExited
        // TODO add your handling code here:
        SociosBtn.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_SociosBtnMouseExited
    
    private void SociosBtnMouseClicked(java.awt.event.MouseEvent evt) {
    	close();
    	Socios s = new Socios();
    	s.setVisible(true);
    }

    private void IngresosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresosBtnMouseEntered
        // TODO add your handling code here:
        IngresosBtn.setBackground(Color.decode("#CACACA"));
    }//GEN-LAST:event_IngresosBtnMouseEntered

    private void IngresosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresosBtnMouseExited
        // TODO add your handling code here:
        IngresosBtn.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_IngresosBtnMouseExited
    
    private void IngresosBtnMouseClicked(java.awt.event.MouseEvent evt) {
    	close();
    	Ingresos i = new Ingresos();
    	i.setVisible(true);
    }

    private void PagosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PagosBtnMouseEntered
        // TODO add your handling code here:
        PagosBtn.setBackground(Color.decode("#CACACA"));
    }//GEN-LAST:event_PagosBtnMouseEntered

    private void PagosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PagosBtnMouseExited
        // TODO add your handling code here:
        PagosBtn.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_PagosBtnMouseExited
    
    private void PagosBtnMouseClicked(java.awt.event.MouseEvent evt) {
    	close();
    	Pagos p = new Pagos();
    	p.setVisible(true);
    }

    private void InformeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformeBtnMouseEntered
        // TODO add your handling code here:
        InformeBtn.setBackground(Color.decode("#CACACA"));
    }//GEN-LAST:event_InformeBtnMouseEntered

    private void InformeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformeBtnMouseExited
        // TODO add your handling code here:
        InformeBtn.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_InformeBtnMouseExited
    
    private void InformeBtnMouseClicked(java.awt.event.MouseEvent evt) {
    	close();
    	Informe i = new Informe();
    	i.setVisible(true);
    }

    private void ListaEsperaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaEsperaBtnMouseEntered
        // TODO add your handling code here:
        ListaEsperaBtn.setBackground(Color.decode("#CACACA"));
    }//GEN-LAST:event_ListaEsperaBtnMouseEntered

    private void ListaEsperaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaEsperaBtnMouseExited
        // TODO add your handling code here:
        ListaEsperaBtn.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_ListaEsperaBtnMouseExited
    
    private void ListaEsperaBtnMouseClicked(java.awt.event.MouseEvent evt) {
    	close();
    	ListaEspera l = new ListaEspera();
    	l.setVisible(true);
    }
    
    private void close() {
    	WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    	Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CopyrightTxt;
    private javax.swing.JPanel ExitBtn;
    private javax.swing.JLabel ExitTxt;
    private javax.swing.JPanel InformeBtn;
    private javax.swing.JLabel InformeIcon;
    private javax.swing.JLabel InformeTxt;
    private javax.swing.JPanel IngresosBtn;
    private javax.swing.JLabel IngresosIcon;
    private javax.swing.JLabel IngresosTxt;
    private javax.swing.JPanel ListaEsperaBtn;
    private javax.swing.JLabel ListaEsperaIcon;
    private javax.swing.JLabel ListaEsperaTxt;
    private javax.swing.JPanel MinimizeBtn;
    private javax.swing.JLabel MinimizeTxt;
    private javax.swing.JPanel PagosBtn;
    private javax.swing.JLabel PagosIcon;
    private javax.swing.JLabel PagosTxt;
    private javax.swing.JPanel SociosBtn;
    private javax.swing.JLabel SociosIcon;
    private javax.swing.JLabel SociosTxt;
    private javax.swing.JToolBar ToolBar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.Box.Filler toolBarFiller;
    // End of variables declaration//GEN-END:variables
}
