/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.galliard.contasoc.gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;

/**
 *
 * @author jomaa
 */
@SuppressWarnings("serial")
public class IngresosFrame extends javax.swing.JFrame {
	private NewMainWindow nmw;
    /**
     * Creates new form IngresosFrame
     */
    public IngresosFrame() {
        initComponents();
        setLocationRelativeTo(nmw);
    }
    
    @Override
	public Image getIconImage() {
		Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/newlogo.png"));
		return retValue;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresosPopupPanel = new javax.swing.JPanel();
        ingresosPopupTablaPanel = new javax.swing.JScrollPane();
        ingresosPopupTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(1, 102, 255));
        setResizable(false);
        setIconImage(getIconImage());

        ingresosPopupPanel.setBackground(new java.awt.Color(1, 102, 255));
        ingresosPopupPanel.setForeground(new java.awt.Color(255, 255, 255));

        ingresosPopupTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Concepto", "Cantidad", "Tipo"
            }
        ) {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @SuppressWarnings("rawtypes")
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ingresosPopupTabla.setFocusable(false);
        ingresosPopupTabla.getTableHeader().setReorderingAllowed(false);
        ingresosPopupTablaPanel.setViewportView(ingresosPopupTabla);
        if (ingresosPopupTabla.getColumnModel().getColumnCount() > 0) {
            ingresosPopupTabla.getColumnModel().getColumn(0).setResizable(false);
            ingresosPopupTabla.getColumnModel().getColumn(0).setPreferredWidth(40);
            ingresosPopupTabla.getColumnModel().getColumn(1).setResizable(false);
            ingresosPopupTabla.getColumnModel().getColumn(1).setPreferredWidth(90);
            ingresosPopupTabla.getColumnModel().getColumn(2).setResizable(false);
            ingresosPopupTabla.getColumnModel().getColumn(2).setPreferredWidth(40);
            ingresosPopupTabla.getColumnModel().getColumn(3).setResizable(false);
            ingresosPopupTabla.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        javax.swing.GroupLayout ingresosPopupPanelLayout = new javax.swing.GroupLayout(ingresosPopupPanel);
        ingresosPopupPanel.setLayout(ingresosPopupPanelLayout);
        ingresosPopupPanelLayout.setHorizontalGroup(
            ingresosPopupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresosPopupTablaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        ingresosPopupPanelLayout.setVerticalGroup(
            ingresosPopupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresosPopupPanelLayout.createSequentialGroup()
                .addComponent(ingresosPopupTablaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresosPopupPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ingresosPopupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTabla() {
    	return ingresosPopupTabla;
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(NewMainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ingresosPopupPanel;
    private javax.swing.JTable ingresosPopupTabla;
    private javax.swing.JScrollPane ingresosPopupTablaPanel;
    // End of variables declaration//GEN-END:variables
}
